apiVersion: v1
kind: Pod
metadata:
  labels:
    run: perfpulse
  name: perfpulse
  namespace: skaha-system
spec:
  serviceAccountName: skaha
  containers:
  - image: opencadc/perfpulse:latest
    name: debug
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
    tty: true
    stdin: true
  dnsPolicy: ClusterFirst
  restartPolicy: Never
